server:
  port: 9000
spring:
  boot:
    admin:
      ui:
        title: ${UI_TITLE:Mcdull Monitor}
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>${spring.boot.admin.ui.title}</span>
        discovery:
          # seata 不具有健康检查的能力 防止报错排除掉
          ignored-services: seata-server