server:
  port: 8091
spring:
  application:
    name: mcdull-mdc-provider
  datasource:
    url: jdbc:mysql://mcdull.io:3306/mcdull-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: mcdull.io
mcdull:
  feign:
    uac: mcdull-uac-provider
#请勿使用相对路径
logging:
  file:
    path: /var/log
    # springboot admin 监控指定log文件
    name: /var/log/mcdull-mdc/out.log


