server:
  port: 8091
spring:
  application:
    name: mcdull-mdc-provider
  datasource:
    url: jdbc:mysql://mcdull.io:3306/mcdull-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: mcdull.io
  #邮件配置样例
  mail:
    host: smtp.sina.com
    username: xxxxx@sina.com
    password: xxxxxxx
    port: 465
    properties:
      smtp:
        auth: true
        timeout: 2500
      mail:
        smtp:
          ssl:
            enable: true
# 指定日志的文件名（nacos）
logging:
  dataId: log
mcdull:
  feign:
    uac: mcdull-uac-provider


