server:
  port: 8090
spring:
  application:
    name: mcdull-uac-provider
mcdull:
  feign:
    uac: mcdull-uac-provider
logging:
  file:
    path: /var/log
    # springboot admin 监控指定log文件
    name: /var/log/mcdull-uac/out.log
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)