server:
  port: 8090
spring:
  application:
    name: mcdull-uac-provider
  datasource:
    url: jdbc:mysql://mcdull.io:3306/mcdull-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: mcdull.io
# 指定日志的文件名（nacos）
logging:
  dataId: log
mcdull:
  feign:
    uac: mcdull-uac-provider