server:
  port: 8082
spring:
  application:
    name: mcdull-dict-provider
  cloud:
    gateway:
      discovery:
        locator:
          #微服务名称以小写形式呈现
          lower-case-service-id: true
# 指定日志的文件名（nacos）
logging:
  dataId: log
