server:
  port: 9090
spring:
  cache:
    type: caffeine
  cloud:
    gateway:
      discovery:
        locator:
          #微服务名称以小写形式呈现
          lower-case-service-id: true
          enabled: true
      routes:
        - id: mcdull-uac-provider
          uri: lb://mcdull-uac-provider
          predicates:
            - Path=/uac/**
          filters:
            - StripPrefix=1
        - id: mcdull-mdc-provider
          uri: lb://mcdull-mdc-provider
          predicates:
            - Path=/mdc/**
          filters:
            - StripPrefix=1
mcdull:
  filter:
    noAuth:
      - /uac/login
  feign:
    uac: mcdull-uac-provider
#请勿使用相对路径
logging:
  file:
    path: /var/log
    # springboot admin 监控指定log文件
    name: /var/log/mcdull-gateway/out.log