server:
  port: 8080
spring:
  application:
    name: mcdull-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #微服务名称以小写形式呈现
          lower-case-service-id: true
          enabled: true
# 指定日志的文件名（nacos）
logging:
  dataId: log