server:
  port: 9090
spring:
  application:
    name: mcdull-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #微服务名称以小写形式呈现
          lower-case-service-id: true
          enabled: true
      routes:
        - id: mcdull-uac-provider
          uri: lb://mcdull-uac-provider
          predicates:
            - Path=/uac/**
          filters:
            - StripPrefix=1
        - id: mcdull-mdc-provider
          uri: lb://mcdull-mdc-provider
          predicates:
            - Path=/mdc/**
          filters:
            - StripPrefix=1
  redis:
    host: mcdull.io
    database: 1
# 指定日志的文件名（nacos）
logging:
  dataId: log

mcdull:
  filter:
    noAuth:
      - /uac/login
  feign:
    uac: mcdull-uac-provider