spring:
  datasource:
    url: jdbc:mysql://mcdull.io:3306/mcdull-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    poolType: Druid  # 指定对应的数据库连接池内置 Druid、Hikari
  redis:
    host: mcdull.io
  data:
    mongodb:
      uri: mongodb://admin:123456@mcdull.io:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-1
logging:
  level:
    root: info
    io.gitee.dqcer.mcdull.framework: info